# ruff: noqa: F403 F405

#
# Settings load order:
#
# - settings_django.py  : Defaults from Django (do not edit)
# - settings-ansible.py : Generated by Ansible (do not edit/commit)
# - mods/*/settings.py  : Modular system (do not edit)
# - settings.py         : The project specific settings (this file)
# - settings_local.py   : Local settings (do not commit)
#

# Standard Library
from socket import getfqdn

# Project
from project.settings_ansible import *


# Applications
INSTALLED_APPS += [
]

# Static files
STATICFILES_DIRS.append(BASE_DIR / 'project' / 'static')

# Templates
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'project' / 'templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# Emails
ADMINS = ()
MANAGERS = ADMINS

fqdn = getfqdn()
DEFAULT_FROM_EMAIL = 'webmaster@' + fqdn
SERVER_EMAIL = 'root@' + fqdn

# Local settings, these should not be committed
try:
    from .settings_local import *
except ImportError:
    pass
