# ruff: noqa: F403 F405

#
# Settings load order:
#
# - settings_django.py  : Defaults from Django (do not edit)
# - settings_ansible.py : Generated by Ansible (do not edit/commit)
# - mods/*/settings.py  : Modular system (do not edit)
# - settings.py         : The project specific settings (this file)
# - settings_local.py   : Local settings (do not commit)
#

# Standard Library
import socket

# Project
from project.settings_ansible import *


# Applications
INSTALLED_APPS += [
]

# Static files
STATICFILES_DIRS.append(BASE_DIR / 'project' / 'static')

# Logging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    "filters": {
        "require_debug_false": {
            "()": "django.utils.log.RequireDebugFalse",
        },
        "require_debug_true": {
            "()": "django.utils.log.RequireDebugTrue",
        },
    },
    'formatters': {
        "default": {
            "()": "django.utils.log.ServerFormatter",
            'style': '{',
            'fmt': '[{asctime}] {levelname} {name} {message}',
            'datefmt': '%d/%m/%Y:%H:%M:%S %z',  # 22/Mar/2025:10:05:09 +0100
        },
        'uvicorn.access': {
            '()': 'uvicorn.logging.AccessFormatter',
            'style': '{',
            'fmt': '[{asctime}] {levelname} {name} "{request_line}" {status_code}',
            'datefmt': '%d/%m/%Y:%H:%M:%S %z',  # 22/Mar/2025:10:05:09 +0100
        },
    },
    'handlers': {
        "stdout": {
            "class": "logging.StreamHandler",
            'stream': 'ext://sys.stdout',
            "formatter": "default",
        },
        "mail_admins": {
            "class": "django.utils.log.AdminEmailHandler",
            "filters": ["require_debug_false"],
            "level": "ERROR",
        },
        'uvicorn.access': {
            'class': 'logging.StreamHandler',
            'stream': 'ext://sys.stdout',
            'formatter': 'uvicorn.access',
        },
    },
    'loggers': {
        # Catch everything, log to standard output
        '': {
            'handlers': ['stdout'],
            'level': 'INFO',
        },
        # Send emails to admins for errors
        "django": {
            "handlers": ["mail_admins"],
            "level": "INFO",
            'propagate': True,
        },
        # Override default uvicorn logging configuration
        'uvicorn': {
            'propagate': True,
        },
        'uvicorn.access': {
            'handlers': ['uvicorn.access'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# Templates
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'project' / 'templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# Emails
ADMINS = ()
MANAGERS = ADMINS

fqdn = socket.getfqdn()
DEFAULT_FROM_EMAIL = 'webmaster@' + fqdn
SERVER_EMAIL = 'root@' + fqdn

# Local settings, these should not be committed
try:
    from .settings_local import *
except ImportError:
    pass
