#
# Define vars from facts
#
# Input :
# Output: name
# Output: dir_root, dir_var, dir_run, dir_etc, dir_log
# Output: file_sock, file_fifo, file_pid
# Requires:
#

# Find out root directory & projct name
- name: "Find out working tree root directory"
  command: "git rev-parse --show-toplevel"
  register: "dir_root"
  changed_when: false
- set_fact:
    dir_root: "{{ dir_root.stdout }}"

- set_fact:
    name: "{{ dir_root|basename }}"

#
# Directories
#

- set_fact:
    dir_var   : "{{ dir_root }}/var"
    dir_run   : "{{ dir_root }}/var/run"
    dir_etc   : "{{ dir_root }}/var/etc"
    dir_log   : "{{ dir_root }}/var/log"
    dir_static: "{{ dir_root }}/var/static"
    dir_media : "{{ dir_root }}/var/media"

- name: "Create directories"
  file:
    path: "{{ item }}"
    state: "directory"
  with_items:
  - "{{ dir_var }}"
  - "{{ dir_run }}"
  - "{{ dir_etc }}"
  - "{{ dir_log }}"
  - "{{ dir_static }}"
  - "{{ dir_media }}"

#
# Variables
#
- set_fact:
    file_sock: "{{ dir_run }}/uwsgi.socket"
    file_fifo: "{{ dir_run }}/uwsgi.fifo"
    file_pid : "{{ dir_run }}/uwsgi.pid"
