- include: "init.yml"
- include: "venv.yml"
- include: "settings.yml"
- include: "database.yml"
- include: "uwsgi.yml"

- include: "static.yml"
  when: "django_with_nginx"

- include: "nginx.yml"
  when: "django_with_nginx"

- include: "monit.yml"
  when: "django_with_monit"
