#
# Git pull
#
# Input :
# Output: dir_root, name
# Requires:
#

# Find out repo
- name: "Find out Git url"
  command: "git config --get remote.origin.url"
  register: "repo"
  changed_when: false
- set_fact:
    repo: "{{ repo.stdout }}"

# Find out dir_root & name
#- set_fact:
#    name: "{{ repo|basename|regex_replace('.git$', '') }}"
#
#- name: "Expand prefix"              # Ansible 2: not needed anymore (use ~)
#  command: "realpath {{ prefix }}"
#  register: "prefix"
#  changed_when: false
#- set_fact:
#    prefix: "{{ prefix.stdout }}"
#
#- set_fact:
#    dir_root: "{{ prefix }}/{{ name }}"
#

- name: "Git pull"
  #git: "repo=file:///{{ cwd }} dest={{ dir_root }}"
  git: "repo={{ repo }} dest={{ dir_root }}"
