#
# Find out root directory
#
# Input   :
# Output  : django_root
# Requires:
#

- name: "Find out working tree root directory"
  command: "git rev-parse --show-toplevel"
  args:
    warn: false
  register: "__aux"
  changed_when: false

- set_fact:
    django_root: "{{ __aux.stdout }}"
