#
# Expand root directory
#
# Input   : django_root
# Output  : django_root
# Requires:
#

- name: "Expand root"
  command: "realpath {{ django_root }}"
  register: "__aux"
  changed_when: false

- set_fact:
    django_root: "{{ __aux.stdout }}"
