- name: "Deploy update in a server"
  hosts: "localhost"
  vars_files:
  - "vars.yml"

  tasks:

  # Find out repo
  - name: "Find out Git url"
    command: "git config --get remote.origin.url"
    register: "repo"
    changed_when: false
  - set_fact:
      repo: "{{ repo.stdout }}"

  # Find out root & name
  - set_fact:
      name: "{{ repo|basename|regex_replace('.git$', '') }}"

  - name: "Expand prefix"              # Ansible 2: not needed anymore (use ~)
    command: "realpath {{ prefix }}"
    register: "prefix"
    changed_when: false
  - set_fact:
      prefix: "{{ prefix.stdout }}"

  - set_fact:
      root: "{{ prefix }}/{{ name }}"

  #
  # Variables
  #
  - set_fact:
      sock: "{{ root }}/var/run/uwsgi.socket"
      fifo: "{{ root }}/var/run/uwsgi.fifo"
      pid : "{{ root }}/var/run/uwsgi.pid"

  #
  # Includes
  #
  - include: "tasks/pull.yml"
  - include: "tasks/venv.yml"
  - include: "tasks/settings.yml"
  - include: "tasks/database.yml"

  #
  # etc (uwsgi, nginx, monit)
  #
  - name: "Create etc dir"
    file:
      path: "{{ root }}/etc"
      state: "directory"

  - name: "Uwsgi configuration"
    template:
      src: "templates/uwsgi.ini.j2"
      dest: "{{ root }}/etc/uwsgi.conf"
    notify: "reload uwsgi"

  - name: "Nginx configuration"
    template:
      src: "templates/nginx.conf.j2"
      dest: "{{ root }}/etc/nginx.conf"
    notify: "reload nginx"

  - name: "Monit configuration"
    template:
      src: "templates/monit.conf.j2"
      dest: "{{ root }}/etc/monit.conf"
    notify: "restart monit"

  #
  # sudo (nginx, monit)
  #
  - name: "(sudo) Nginx: mkdir /etc/nginx/sites"
    file: "path=/etc/nginx/sites state=directory"
    sudo: true

  - name: "Nginx symlink"
    file:
      path: "/etc/nginx/sites/{{ name }}.conf"
      state: "link"
      src: "{{ root }}/etc/nginx.conf"
    notify: "reload nginx"
    sudo: true

  - name: "(sudo) Monit: mkdir /etc/monit.d"
    file: "path=/etc/monit.d state=directory"
    sudo: true

  - name: "Monit symlink"
    file:
      path: "/etc/monit.d/{{ name }}.conf"
      state: "link"
      src: "{{ root }}/etc/monit.conf"
    notify: "restart monit"
    sudo: true

  #
  # Handlers
  #
  handlers:
  - name: "reload uwsgi"
    command: "echo r > {{ fifo }}"

  - name: "reload nginx"
    service: "name=nginx state=reloaded"
    sudo: true

  - name: "restart monit"
    service: "name=monit state=restarted"
    sudo: true
