#
# See roles/django/defaults/main.yml for the available options
#

- name: "Development"
  hosts: "hosts"
  vars_files:
  - "vars.yml"
  roles:
  - role              : "jdavid.django"
    django_pull       : false
    django_with_monit : false

    database:
      engine          : "postgres"
      name            : "django-boot"
      user            : "django-boot"
      password        : "django-boot"

    django            :
      debug           : true
      port            : 8000

    supervisor:
      daemon          : false
