#
# See roles/django/defaults/main.yml for the available options
#

- name: "Development"
  hosts: "hosts"
  vars_files:
  - "vars.yml"
  roles:
  - role              : "jdavid.django"
    django_pull       : false
    django_with_monit : false

    database:
      engine          : "sqlite"

    django            :
      debug           : true
      port            : 8000

    mods:
    - "mods.sendfile"
    - "mods.vite"

    supervisor:
      daemon          : false
