#
# See roles/django/defaults/main.yml for the available options
#

- name: "Development"
  hosts: "development"
  vars_files:
  - "vars.yml"
  roles:
  - role              : "jdavid.django"
    django_debug      : true
    django_pull       : false
    django_with_nginx : false
    django_with_monit : false
    django_with_sudo  : false

    django_domain     : "{{ ansible_default_ipv4.address }}.xip.io"
    django_root       : ""
    django_name       : ""

    django_database   :
      engine          : "sqlite"
