#
# See roles/django/defaults/main.yml for the available options
#

- name: "Production"
  hosts: "hosts"
  vars_files:
  - "vars.yml"
  roles:
  - role: "jdavid.django"
    django_debug      : false
    django_pull       : true
    django_with_monit : true

    #django_domain     : ""
    django_name       : "django-boot-production"

    django_cache:
      backend         : "memcached"
      location        : "unix:/run/memcached/memcached.sock"

    django_database:
      engine          : "postgres"
      name            : ""
      user            : ""
      password        : ""

    django_server:
      workers         : 6

    django_cert:
      email           : ""

    nginx:
      http            : true
      https           : false

    supervisor:
      daemon          : true
