#
# See roles/django/defaults/main.yml for the available options
#

- name: "Production"
  hosts: "hosts"
  vars_files:
  - "vars.yml"
  roles:
  - role: "jdavid.django"
    django_pull       : true
    django_with_monit : true

    django_name       : "django-boot-production"

    django            :
      debug           : false
      workers         : 4

    mods:
    - "mods/admin"
    - "mods/compress"
    - "mods/dotenv"
    - "mods/memcached"
    - "mods/ping"
    - "mods/postgres"
    - "mods/uvicorn"

    postgres:
      name            : ""
      user            : ""
      password        : ""

    django_cert:
      email           : ""

#   domains          :
#   - ""

    nginx:
      http            : true
      https           : false

    supervisor:
      daemon          : true
