#
# See roles/django/defaults/main.yml for the available options
#

- name: "Production"
  hosts: "production"
  vars_files:
  - "vars.yml"
  roles:
  - role: "django"
    django_database   : "postgres"
    django_debug      : false
    #django_domain    : "{{ ansible_default_ipv4.address }}.xip.io"
    django_pull       : false
    django_with_nginx : true
    django_with_monit : true
    django_with_sudo  : false

    django_root       : "/tmp/django-boot-production"
    django_name       : "django-boot-production"
