#
# See roles/django/defaults/main.yml for the available options
#

- name: "Production"
  hosts: "hosts"
  vars_files:
  - "vars.yml"
  roles:
  - role: "jdavid.django"
    django_pull       : true
    django_with_monit : true

    django_name       : "django-boot-production"

    cache:
      backend         : "memcached"
      location        : "unix:/run/memcached/memcached.sock"

    database:
      engine          : "postgres"
      name            : ""
      user            : ""
      password        : ""

    django            :
      debug           : false
      workers         : 6

    mods:
    - "mods.sendfile"
    - "mods.vite"

    django_cert:
      email           : ""

#   domains          :
#   - ""

    nginx:
      http            : true
      https           : false

    supervisor:
      daemon          : true
