#
# See roles/django/defaults/main.yml for the available options
#

- name: "Staging"
  hosts: "staging"
  vars_files:
  - "vars.yml"
  roles:
  - role: "django"
    django_debug      : false
    django_pull       : true
    django_with_nginx : true
    django_with_monit : true
    django_with_sudo  : false

    #django_domain     : ""
    django_name       : "django-boot-staging"
    django_root       : "/tmp/django-boot-staging"

    django_database   :
      engine          : "sqlite"
