#
# See roles/django/defaults/main.yml for the available options
#

- name: "Staging"
  hosts: "staging"
  roles:
  - role: "django"
    django_database   : "sqlite"
    django_debug      : false
    #django_domain    : "{{ ansible_default_ipv4.address }}.xip.io"
    django_pull       : false
    django_with_nginx : true
    django_with_monit : true
    django_with_sudo  : false
